### ISSUE TITLE
Covoid train  with reinfoselect

### ISSUE THREAD

**Issue by xiaohong020408** [thunlp/OpenMatch#7]
when I  run this.  I got error.

CUDA_VISIBLE_DEVICES=0 \
python train.py \
        -task ranking \
        -model bert \
        -reinfoselect \
        -train ./data/seanmed.train.320K-pairs.jsonl \
        -max_input 1280000 \
        -save ./checkpoints/reinfoselect_scibert_rl.bin \
        -dev ./data/covoid/dev_trec-covid-round1.jsonl \
        -qrels ./data/covoid/qrels-cord19-round1.txt \
        -vocab ./pretrain_models/scibert \
        -pretrain ./pretrain_models/scibert \
        -res ./results/scibert_rl.trec \
        -metric ndcg_cut_10 \
        -max_query_len 32 \
        -max_doc_len 256 \
        -epoch 5 \
        -batch_size 16 \
        -lr 2e-5 \
        -tau 1 \
        -n_warmup_steps 1000 \
        -eval_every 1

reading training data...
reading dev data...
Namespace(batch_size=16, checkpoint=None, dev='./data/covoid/dev_trec-covid-round1.jsonl', ent_vocab='', epoch=5, eval_every=1, lr=2e-05, max_doc_len=256, max_input=1280000, max_query_len=32, metric='ndcg_cut_10', mode='cls', model='bert', n_kernels=21, n_warmup_steps=1000, pretrain='./pretrain_models/scibert', qrels='./data/covoid/qrels-cord19-round1.txt', reinfoselect=True, res='./results/scibert_rl.trec', reset=False, save='./checkpoints/reinfoselect_scibert_rl.bin', task='ranking', tau=1.0, train='./data/seanmed.train.320K-pairs.jsonl', vocab='./pretrain_models/scibert')
save_model...
initial result:  0.0077274006084700605
Traceback (most recent call last):
  File "train.py", line 601, in <module>
    main()
  File "train.py", line 596, in main
    train_reinfoselect(args, model, policy, loss_fn, m_optim, m_scheduler, p_optim, metric, train_loader, dev_loader, device)
  File "train.py", line 61, in train_reinfoselect
    for step, train_batch in enumerate(train_loader):
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/bak/hxh/python/openmatch/venv/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/bak/hxh/python/openmatch/OpenMatch-master/OpenMatch/data/datasets/bert_dataset.py", line 172, in __getitem__
    doc_tokens_pos = self._tokenizer.tokenize(example['doc_pos'])[:self._seq_max_len-len(query_tokens)-3]
KeyError: 'doc_pos'

Could you help me ?  Thanks a lot.

**Comment by zkt12** [comment]
Thank you for pointing out this bug. I've made it wrong of the **-task** setting. Since the training data is query-doc pair, not pair-wise (query, positive doc, negative doc), so the *-task* should be set to *classification*.

I've updated this script, you can run **git pull** to get the new settings :)
